### PR TITLE
Palindrome Cpp code

### PR DESCRIPTION
**Pull request by umirz87**
This code contains function called palindrome that checks if input string is plindrom or not
String called plindrom are look like this
E.g: maam i.e read from start or end spellings are same

### CODE REVIEW

**Comment by umirz87** [comment]
This code contains function called palindrome that checks where input string is plindrom or not 
String called plindrom are look like this
E.g:  maam i.e read from start or end spellings are same

**Comment by Lazeeez** [comment]
@umirz87 this works, add this to the description of the contribution and we're done.

**Comment by umirz87** [comment]
Done

**Comment by umirz87** [comment]
I have added the description kindly accept

**Pull request merged**
